2024-04-03 14:33:53,231 ERROR: Exception on /main/auth/login [GET] [in /Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 844, in dispatch_request
    self.raise_routing_exception(req)
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 453, in raise_routing_exception
    raise request.routing_exception  # type: ignore[misc]
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask/ctx.py", line 362, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/werkzeug/routing/map.py", line 624, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 755, in handle_user_exception
    return self.handle_http_exception(e)
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 730, in handle_http_exception
    return self.ensure_sync(handler)(e)  # type: ignore[no-any-return]
  File "/Users/artyom/WL/flask_tutorial/app/errors/handlers.py", line 8, in not_found_error
    return render_template('errors/404.html'), 404
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/artyom/WL/flask_tutorial/app/templates/errors/404.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/artyom/WL/flask_tutorial/app/templates/base.html", line 20, in top-level template code
    <a class="navbar-brand" href="{{ url_for('index') }}">Microblog</a>
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 1074, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 1063, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/werkzeug/routing/map.py", line 919, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2024-04-03 14:36:41,928 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial/app/__init__.py:79]
2024-04-03 14:36:45,311 ERROR: Exception on / [GET] [in /Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py:828]
Traceback (most recent call last):
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 1463, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 872, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 870, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 855, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask_login/utils.py", line 290, in decorated_view
    return current_app.ensure_sync(func)(*args, **kwargs)
  File "/Users/artyom/WL/flask_tutorial/app/main/routes.py", line 50, in index
    return render_template('index.html', title=_('Home'), form=form,
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask/templating.py", line 150, in render_template
    return _render(app, template, context)
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask/templating.py", line 131, in _render
    rv = template.render(context)
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/Users/artyom/WL/flask_tutorial/app/templates/index.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
  File "/Users/artyom/WL/flask_tutorial/app/templates/base.html", line 58, in top-level template code
    {% block content %}{% endblock %}
  File "/Users/artyom/WL/flask_tutorial/app/templates/index.html", line 10, in block 'content'
    {% include '_post.html' %}
  File "/Users/artyom/WL/flask_tutorial/app/templates/_post.html", line 4, in top-level template code
    <a href="{{ url_for('user', username=post.author.username) }}">
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 1074, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/flask/app.py", line 1063, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "/Users/artyom/WL/flask_tutorial/venv/lib/python3.9/site-packages/werkzeug/routing/map.py", line 919, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'main.user' instead?
2024-04-03 14:37:40,373 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial/app/__init__.py:79]
2024-04-03 16:05:50,953 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 16:06:44,242 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 16:06:44,242 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 16:06:44,242 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 16:06:44,276 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 17:20:38,355 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 17:20:38,355 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 17:20:38,377 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 17:20:38,377 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 17:37:14,293 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 17:37:14,332 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 17:37:14,428 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 17:37:14,495 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 17:52:46,363 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 17:52:46,448 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 17:52:46,533 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 17:52:46,584 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 18:09:05,507 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 18:09:05,600 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 18:09:05,654 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 18:09:05,660 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 18:10:54,718 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 18:10:54,758 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 18:10:54,789 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 18:10:54,877 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 19:02:33,616 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
2024-04-03 19:02:33,616 INFO: Microblog startup [in /Users/artyom/WL/flask_tutorial_all/flask_tutorial/app/__init__.py:79]
